const keysMapRu = {
  Backquote: {
    code: 'Backquote',
    type: 'letter',
    key: 'ё',
    repeat: true,
  },
  Digit1: {
    code: 'Digit1',
    type: 'symbol',
    shifted: '!',
    key: '1',
    repeat: true,
  },
  Digit2: {
    code: 'Digit2',
    type: 'symbol',
    shifted: '"',
    key: '2',
    repeat: true,
  },
  Digit3: {
    code: 'Digit3',
    type: 'symbol',
    shifted: '№',
    key: '3',
    repeat: true,
  },
  Digit4: {
    code: 'Digit4',
    type: 'symbol',
    shifted: ';',
    key: '4',
    repeat: true,
  },
  Digit5: {
    code: 'Digit5',
    key: '5',
    type: 'symbol',
    shifted: '%',
    repeat: true,
  },
  Digit6: {
    code: 'Digit6',
    type: 'symbol',
    shifted: ':',
    key: '6',
    repeat: true,
  },
  Digit7: {
    code: 'Digit7',
    type: 'symbol',
    shifted: '?',
    key: '7',
    repeat: true,
  },
  Digit8: {
    code: 'Digit8',
    type: 'symbol',
    shifted: '*',
    key: '8',
    repeat: true,
  },
  Digit9: {
    code: 'Digit9',
    type: 'symbol',
    shifted: '(',
    key: '9',
    repeat: true,
  },
  Digit0: {
    code: 'Digit0',
    type: 'symbol',
    shifted: ')',
    key: '0',
    repeat: true,
  },
  Minus: {
    code: 'Minus',
    type: 'symbol',
    shifted: '_',
    key: '-',
    repeat: true,
  },
  Equal: {
    code: 'Equal',
    type: 'symbol',
    shifted: '+',
    key: '=',
    repeat: true,
  },
  Backspace: {
    code: 'Backspace',
    type: 'functional',
    key: 'Backspace',
    symbol: '',
    repeat: true,
    style: 'special',
    icon: 'backspace',
  },
  Tab: {
    code: 'Tab',
    type: 'symbol',
    key: 'Tab',
    symbol: '\t',
    repeat: true,
    style: 'special',
    icon: 'keyboard_tab',
  },
  KeyQ: {
    code: 'KeyQ',
    type: 'letter',
    key: 'й',
    repeat: true,
  },
  KeyW: {
    code: 'KeyW',
    type: 'letter',
    key: 'ц',
    repeat: true,
  },
  KeyE: {
    code: 'KeyE',
    type: 'letter',
    key: 'у',
    repeat: true,
  },
  KeyR: {
    code: 'KeyR',
    type: 'letter',
    key: 'к',
    repeat: true,
  },
  KeyT: {
    code: 'KeyT',
    type: 'letter',
    key: 'е',
    repeat: true,
  },
  KeyY: {
    code: 'KeyY',
    type: 'letter',
    key: 'н',
    repeat: true,
  },
  KeyU: {
    code: 'KeyU',
    type: 'letter',
    key: 'г',
    repeat: true,
  },
  KeyI: {
    code: 'KeyI',
    type: 'letter',
    key: 'ш',
    repeat: true,
  },
  KeyO: {
    code: 'KeyO',
    type: 'letter',
    key: 'щ',
    repeat: true,
  },
  KeyP: {
    code: 'KeyP',
    type: 'letter',
    key: 'з',
    repeat: true,
  },
  BracketLeft: {
    code: 'BracketLeft',
    type: 'letter',
    key: 'х',
    repeat: true,
  },
  BracketRight: {
    code: 'BracketRight',
    type: 'letter',
    key: 'ъ',
    repeat: true,
  },
  Backslash: {
    code: 'Backslash',
    type: 'symbol',
    key: '\\',
    shifted: '/',
    repeat: true,
  },
  Delete: {
    code: 'Delete',
    type: 'functional',
    key: 'Del',
    symbol: '',
    repeat: true,
    style: 'special',
  },
  CapsLock: {
    code: 'CapsLock',
    type: 'functional',
    key: 'CapsLock',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'keyboard_capslock',
  },
  KeyA: {
    code: 'KeyA',
    type: 'letter',
    key: 'ф',
    repeat: true,
  },
  KeyS: {
    code: 'KeyS',
    type: 'letter',
    key: 'ы',
    repeat: true,
  },
  KeyD: {
    code: 'KeyD',
    type: 'letter',
    key: 'в',
    repeat: true,
  },
  KeyF: {
    code: 'KeyF',
    type: 'letter',
    key: 'а',
    repeat: true,
  },
  KeyG: {
    code: 'KeyG',
    type: 'letter',
    key: 'п',
    repeat: true,
  },
  KeyH: {
    code: 'KeyH',
    type: 'letter',
    key: 'р',
    repeat: true,
  },
  KeyJ: {
    code: 'KeyJ',
    type: 'letter',
    key: 'о',
    repeat: true,
  },
  KeyK: {
    code: 'KeyK',
    type: 'letter',
    key: 'л',
    repeat: true,
  },
  KeyL: {
    code: 'KeyL',
    type: 'letter',
    key: 'д',
    repeat: true,
  },
  Semicolon: {
    code: 'Semicolon',
    type: 'letter',
    key: 'ж',
    repeat: true,
  },
  Quote: {
    code: 'Quote',
    type: 'letter',
    key: 'э',
    repeat: true,
  },
  Enter: {
    code: 'Enter',
    type: 'symbol',
    key: 'Enter',
    symbol: '\n',
    repeat: true,
    style: 'special',
    icon: 'keyboard_return',
  },
  ShiftLeft: {
    code: 'ShiftLeft',
    type: 'functional',
    key: 'Shift',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'shift',
  },
  KeyZ: {
    code: 'KeyZ',
    type: 'letter',
    key: 'я',
    repeat: true,
  },
  KeyX: {
    code: 'KeyX',
    type: 'letter',
    key: 'ч',
    repeat: true,
  },
  KeyC: {
    code: 'KeyC',
    type: 'letter',
    key: 'с',
    repeat: true,
  },
  KeyV: {
    code: 'KeyV',
    type: 'letter',
    key: 'м',
    repeat: true,
  },
  KeyB: {
    code: 'KeyB',
    type: 'letter',
    key: 'и',
    repeat: true,
  },
  KeyN: {
    code: 'KeyN',
    type: 'letter',
    key: 'т',
    repeat: true,
  },
  KeyM: {
    code: 'KeyM',
    type: 'letter',
    key: 'ь',
    repeat: true,
  },
  Comma: {
    code: 'Comma',
    type: 'letter',
    key: 'б',
    repeat: true,
  },
  Period: {
    code: 'Period',
    type: 'letter',
    key: 'ю',
    repeat: true,
  },
  Slash: {
    code: 'Slash',
    type: 'symbol',
    key: '.',
    shifted: ',',
    repeat: true,
  },
  ShiftRight: {
    code: 'ShiftRight',
    type: 'functional',
    key: 'Shift',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'shift',
  },
  ArrowUp: {
    code: 'ArrowUp',
    type: 'functional',
    key: '▲',
    repeat: true,
    style: 'special',
  },
  Lang: {
    code: 'Lang',
    type: 'functional',
    key: 'Lang',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'language',
  },
  ControlLeft: {
    code: 'ControlLeft',
    type: 'functional',
    key: 'Ctrl',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'keyboard_control_key',
  },
  MetaLeft: {
    code: 'MetaLeft',
    type: 'functional',
    key: 'Meta',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'keyboard_command_key',
  },
  AltLeft: {
    code: 'AltLeft',
    type: 'functional',
    key: 'Alt',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'keyboard_option_key',
  },
  Space: {
    code: 'Space',
    type: 'symbol',
    key: ' ',
    repeat: true,
  },
  AltRight: {
    code: 'AltRight',
    type: 'functional',
    key: 'Alt',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'keyboard_option_key',
  },
  ControlRight: {
    code: 'ControlRight',
    type: 'functional',
    key: 'Ctrl',
    symbol: '',
    repeat: false,
    style: 'special',
    icon: 'keyboard_control_key',
  },
  ArrowLeft: {
    code: 'ArrowLeft',
    type: 'functional',
    key: '◄',
    repeat: true,
    style: 'special',
  },
  ArrowDown: {
    code: 'ArrowDown',
    type: 'functional',
    key: '▼',
    repeat: true,
    style: 'special',
  },
  ArrowRight: {
    code: 'ArrowRight',
    type: 'functional',
    key: '►',
    repeat: true,
    style: 'special',
  },
};

export default keysMapRu;
